name: flutter_siparis_takip
description: Material 3 tabanlı Flutter Sipariş Takip Uygulaması — modern, profesyonel, gradientsiz.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/orders.json
